### ISSUE TITLE
[security] Reset password link

### ISSUE THREAD

**Issue by skotchio** [braitsch/node-login#21]
In your EmailDispatcher https://github.com/braitsch/node-login/blob/master/app/server/modules/email-dispatcher.js you send reset link lik ethe following:

```
var link = 'http://node-login.braitsch.io/reset-password?e='+o.email+'&p='+o.pass;
```

Although that password is hashed I think it's not secure send it to client. It would be more secure as generate another hashed string. What do you think about it?

**Comment by braitsch** [comment]
The password reset link now contains a single use UUID to lookup the user's account and validates against the user's last recorded IP address.
