### ISSUE TITLE
Can't create new user on my local copy (though it appears to work fine on the sample site for which you provided the link).

### ISSUE THREAD

**Issue by devonzuegel** [braitsch/node-login#30]
After cloning the code and running the app locally, everything was working great until I created a new user and clicked submit. Instead of creating the user, the app did nothing (unless there was some error in the for, in which case it would alert me that my password wasn't long enough etc.)

**Comment by braitsch** [comment]
The MongoDB database must be running in the background to add/edit accounts.
In a separate shell type:
```
> mongod
```
