### ISSUE TITLE
"Forgot your password" sends smtp error in console

### ISSUE THREAD

**Issue by anirban93** [braitsch/node-login#32]
#### On console
![errors](https://cloud.githubusercontent.com/assets/5820924/8881359/ffe6fd74-3260-11e5-8217-b94676b47d9d.png)
###### What can be done for it ?

**Comment by braitsch** [comment]
You have to add your gmail credentials to /app/server/modules/email-settings.js if you want to enable the  password retrieval feature. Instructions are in the updated readme.

**Comment by anirban93** [comment]
I added credentials. There is still code 2 and code 3 error. test account doesn't have two step verification.
Smtp says to log in via web browser and try again. But, It doesn't work.

**Comment by braitsch** [comment]
I don't believe [emailjs](https://github.com/eleith/emailjs) supports two step authentication. I'd look through their issues to troubleshoot the specific problem your having.

**Comment by anirban93** [comment]
I don't think any email app without gmail from browser supports that. In that case, Google provides app-specific passwords.
I searched for the error and found that two-step verifications for a account may cause such error. But, the account i used doesn't have it. Google has also sent mail saying that it prevented access from an app that doesn't meet modern security standards.
May be emailjs has to be updated.
