### ISSUE TITLE
Link sign in with HTML Page

### ISSUE THREAD

**Issue by sherbetxia** [braitsch/node-login#37]
Hi, i am new to node.js. I wanted to know whether I could link pages to my html pages after user sign in. Because your code is based on jade and js. I tried to include my html page in a jade file I created (index.jade). It still shows "I'm sorry, the page or resource you are searching for is currently unavailable" .
Can I get any suggestion from you?

**Comment by lifeSo** [comment]
Sorry ,I do not know how to solve it . @sherbetxia

**Comment by zoutepopcorn** [comment]
In routes.js

```	
app.get('/home', function(req, res) {
		if (req.session.user == null){
	// if user is not logged-in redirect back to login page //
			res.redirect('/');
		}	else{
			res.sendFile(__dirname + '/views/html/home.html');
		}
	});
```

Then put a html file in /views/html

Then you can add in route.js to a edit jade file for changing user data. Then you can make a link to it in your html. 

```
	app.get('/edit', function(req, res) {
		if (req.session.user == null){
	// if user is not logged-in redirect back to login page //
			res.redirect('/');
		}	else{
			res.render('home', {
				title : 'Control Panel',
				countries : CT,
				udata : req.session.user
			});
		}
	});

```

I think it would be great to have this working without jade at all also

**Comment by braitsch** [comment]
You can serve static HTML files by simply placing them in the ``/public`` folder in the root directory. Take a look at [Serving static files in Express](https://expressjs.com/en/starter/static-files.html) for more information.
