### ISSUE TITLE
Atomicity violation during user registration

### ISSUE THREAD

**Issue by Annoraaq** [braitsch/node-login#41]
The registering of two users can overlap such that two users with the same username or email are in the database. I suggest adding an index to the email and username fields in the database.

**Comment by braitsch** [comment]
The possibility of this happening is next to zero as once a username or email address is taken it is no longer available to any other user and the ``addNewAccount`` method which validates incoming new account requests returns in a fraction of a second.

**Comment by braitsch** [comment]
[Fair enough.](https://github.com/braitsch/node-login/blob/52c3955d14ff1cef6f9b77256c600005c975f86d/app/server/modules/account-manager.js#L14)
