### ISSUE TITLE
Password reset will fail

### ISSUE THREAD

**Issue by josvaler** [braitsch/node-login#45]
This is because the file email-dispatcher.js has the following line hardcoded:

var link = 'https://nodejs-login.herokuapp.com/reset-password?e='+o.email+'&p='+o.pass;

If you are testing on localhost:3000 eMail points to the wrong link in herokuapp.com.

You can add this as en external variable also, as you did for EMAIL_HOST,EMAIL_USER and EMAIL_PASS

Regards,

J

**Comment by braitsch** [comment]
This is fixed in [v1.7.0](https://github.com/braitsch/node-login/blob/41cd0f78af94cb85f6c0ea5744a823f5ee2c0b7a/app/server/modules/email-dispatcher.js#L26). Thanks.
