### ISSUE TITLE
About the database

### ISSUE THREAD

**Issue by LaviniaJGX** [braitsch/node-login#53]
I don't know how to find the data set in the localhost.
> show dbs
admin       0.000GB
config      0.000GB
local       0.000GB
node-login  0.000GB

There is nothing in the database.How to find the data?

**Comment by braitsch** [comment]
Look at the [print method](https://github.com/braitsch/node-login/blob/master/app/server/routes.js#L167) inside of the Express app. This queries the database and returns all of the accounts that are in the accounts collection and displays the results at http://localhost:3000/print
