### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by Buubiye** [braitsch/node-login#61]
Hi, the https://nodejs-login.herokuapp.com/ website is down. The reason this repo was successful is because of that quick demo site. Please fix it asap. 

I think the reason this site is not working is because heroku discontinued some of its most useful add-ons like mlab database add-on.

**Comment by braitsch** [comment]
I just updated the demo and moved it to https://node-login.braitsch.io/

If you're enjoying this project, considering throwing a few bucks in the pot to support its ongoing development https://node-login.braitsch.io/support
